name: SOPS Exec
description: Decrypts environment variables using sops
runs:
  using: composite
  steps:
    # Check if the required tools are installed and get their versions
    - name: Check requirements
      id: check-requirements
      shell: bash
      run: |

        ## age
        if ! command -v age &> /dev/null
        then
          echo "::error ::age could not be found"
          exit 1
        fi
        AGE_VERSION=$(age --version)

        # Write the extracted version to a GitHub output variable
        echo "age-version=$AGE_VERSION" >> $GITHUB_OUTPUT

        ## sops
        if ! command -v sops &> /dev/null
        then
          echo "::error ::sops could not be found"
          exit 1
        fi
        SOPS_VERSION=$(sops --version)

        # Write the extracted version to a GitHub output variable
        echo "sops-version=$SOPS_VERSION" >> $GITHUB_OUTPUT

    # Execute the run clause and pass the decrypted environment variables (or file) to it
    - name: Execute the run clause
      id: sops-exec
      shell: bash
      run: |
        echo "TODO sops exec-env/exec-file ..."
