name: SOPS Exec
description: A GitHub Action for securely executing commands with secrets.
author: LNSD
branding:
  color: gray-dark
  icon: lock
inputs:
  env_file:
    description: 'The environment file to decrypt and pass to the command'
    required: true
  run:
    description: 'The command to run'
    required: true
runs:
  using: composite
  steps:
    # Check if the required tools are installed and get their versions
    - name: Check pre-requisites
      id: check-pre-requisites
      shell: bash
      run: |
        # Check pre-requisites
        source ./action.sh

        action::check_pre_requisites

    # Execute the command and pass the decrypted environment variables (or file) to it
    - name: Execute the command
      id: sops-exec
      shell: bash
      run: |
        # Execute the command
        source ./action.sh

        action::main "${{ inputs.env_file }}" "${{ inputs.run }}"
