name: test
on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Setup yamllint
        run: sudo apt-get install -y yamllint

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@dae28e5c0d0d2ecf297b7d8d1ae143f464ca3ee8 # 1.5.5
        with:
          bats-version: 1.10.0
          support-version: 0.3.0
          assert-version: 2.1.0
          detik-install: false
          file-version: 0.4.0

      - name: Setup age
        uses: alessiodionisi/setup-age-action@82b9aea163ade7fe23441552a514cf666b214077 # v1.3.0
        with:
          version: 1.1.1

      - name: Setup sops
        uses: nhedger/setup-sops@358bac533e4e92f9ce9f9da563d6265929c88cda # v2
        with:
          version: 3.8.1

      - run: make check-testlib
      - run: make test-testlib

      - run: make check
      - run: make unittest
      - run: make inttest

